// Generated by CoffeeScript 2.3.1
(function() {
  var _, bizday, moment, test;

  _ = require('lodash-core');

  bizday = require('../');

  moment = require('../lib/moment-with-locales.min.js');

  ({test} = require('ava'));

  test('buildCalendar()', function(t) {
    return t.true(bizday.buildCalendar().length >= 365);
  });

  test('buildCalendar("notObject")', function(t) {
    var e;
    e = t.throws(function() {
      return bizday.buildCalendar("notObject");
    });
    return t.is(e.message, 'Argument requires object type');
  });

  test('buildCalendar(opts)', function(t) {
    var opts;
    opts = {
      startYear: 2016,
      endYear: 2017
    };
    return t.true(bizday.buildCalendar(opts).length === 731);
  });

  test('buildCalendar(omitWeekEnd)', function(t) {
    var opts;
    opts = {
      startYear: 2016,
      endYear: 2017,
      omitWeekEnd: true
    };
    return t.true(bizday.buildCalendar(opts).length === 521);
  });

  test('buildCalendar(Invalid value)', function(t) {
    var opts;
    opts = {
      startYear: 'Invalid',
      endYear: 'value'
    };
    return t.true(bizday.buildCalendar(opts).length >= 365);
  });

}).call(this);
