// Generated by CoffeeScript 2.3.1
(function() {
  var _, bizday, moment, test;

  _ = require('lodash');

  bizday = require('../');

  moment = require('moment');

  ({test} = require('ava'));

  test('reject with string', function(t) {
    var bd;
    bd = new bizday('20151231', {
      reject: ['2016']
    });
    t.is(bd.val(), '20151231');
    return t.is(bd.add(), '20170102');
  });

  test('reject with string (not array)', function(t) {
    var bd;
    bd = new bizday('20151231', {
      reject: '2016'
    });
    t.is(bd.val(), '20151231');
    return t.is(bd.add(), '20170102');
  });

  test('reject with string 2', function(t) {
    var bd;
    bd = new bizday('20151231', {
      reject: ['2016', '01-02']
    });
    t.is(bd.val(), '20151231');
    return t.is(bd.add(), '20170103');
  });

  test('reject with regex', function(t) {
    var bd;
    bd = new bizday('20151231', {
      reject: [/2016/]
    });
    t.is(bd.val(), '20151231');
    return t.is(bd.add(), '20170102');
  });

  test('reject with regex (not array)', function(t) {
    var bd;
    bd = new bizday('20151231', {
      reject: /2016/
    });
    t.is(bd.val(), '20151231');
    return t.is(bd.add(), '20170102');
  });

  test('reject with regex 2', function(t) {
    var bd;
    bd = new bizday('20151231', {
      reject: [/01-01/, /01-02/]
    });
    t.is(bd.val(), '20151231');
    return t.is(bd.add(), '20160104');
  });

  test('reject with regex and string', function(t) {
    var bd;
    bd = new bizday('20151231', {
      reject: [/2016/, '01-02', /01-03/]
    });
    t.is(bd.val(), '20151231');
    return t.is(bd.add(), '20170104');
  });

}).call(this);
