// Generated by CoffeeScript 2.3.1
(function() {
  var _, bizday, moment, test;

  _ = require('lodash');

  bizday = require('../');

  moment = require('moment');

  ({test} = require('ava'));

  test('reject with string', function(t) {
    var bd;
    bd = new bizday('2015-12-31', {
      reject: ['2016']
    });
    t.is(bd.val(), '2015-12-31');
    return t.is(bd.add(), '2017-01-02');
  });

  test('reject with string (not array)', function(t) {
    var bd;
    bd = new bizday('2015-12-31', {
      reject: '2016'
    });
    t.is(bd.val(), '2015-12-31');
    return t.is(bd.add(), '2017-01-02');
  });

  test('reject with string 2', function(t) {
    var bd;
    bd = new bizday('2015-12-31', {
      reject: ['2016', '01-02']
    });
    t.is(bd.val(), '2015-12-31');
    return t.is(bd.add(), '2017-01-03');
  });

  test('reject with regex', function(t) {
    var bd;
    bd = new bizday('2015-12-31', {
      reject: [/2016/]
    });
    t.is(bd.val(), '2015-12-31');
    return t.is(bd.add(), '2017-01-02');
  });

  test('reject with regex (not array)', function(t) {
    var bd;
    bd = new bizday('2015-12-31', {
      reject: /2016/
    });
    t.is(bd.val(), '2015-12-31');
    return t.is(bd.add(), '2017-01-02');
  });

  test('reject with regex 2', function(t) {
    var bd;
    bd = new bizday('2015-12-31', {
      reject: [/01-01/, /01-02/]
    });
    t.is(bd.val(), '2015-12-31');
    return t.is(bd.add(), '2016-01-04');
  });

  test('reject with regex and string', function(t) {
    var bd;
    bd = new bizday('2015-12-31', {
      reject: [/2016/, '01-02', /01-03/]
    });
    t.is(bd.val(), '2015-12-31');
    return t.is(bd.add(), '2017-01-04');
  });

}).call(this);
