// Generated by CoffeeScript 2.3.1
(function() {
  var _, bizday, moment, test;

  _ = require('lodash');

  bizday = require('../');

  moment = require('moment');

  ({test} = require('ava'));

  test.skip('constructor date 01', function(t) {
    var bd;
    bd = new bizday();
    bd.val(); // '現在の日付'
    bd.add(); // '翌営業日の日付'
  });

  test('constructor date 02', function(t) {
    var bd;
    bd = new bizday('2018-01-01');
    t.is(bd.val(), '2018-01-01');
    t.is(bd.add(), '2018-01-02');
  });

  test('constructor date 03', function(t) {
    var bd;
    bd = new bizday('20180101');
    t.is(bd.val(), '2018-01-01');
    t.is(bd.add(), '2018-01-02');
  });

  test('constructor format 01', function(t) {
    var bd;
    bd = new bizday('2018-01-01', {
      format: ''
    });
    t.is(bd.val(), '2018-01-01T00:00:00+09:00');
    t.is(bd.add(), '2018-01-02T00:00:00+09:00');
  });

  test('constructor format 02', function(t) {
    var bd;
    bd = new bizday('2018-01-01', {
      format: 'YYYYMMDD'
    });
    t.is(bd.val(), '20180101');
    t.is(bd.add(), '20180102');
  });

  test('constructor type', function(t) {
    var bd;
    bd = new bizday('2017-12-31', {
      type: 'jp'
    });
    t.is(bd.val(), '2017-12-31');
    t.is(bd.add(), '2018-01-02');
  });

  test('constructor reject 01', function(t) {
    var bd;
    bd = new bizday('2018-01-01', {
      reject: '-01-02'
    });
    t.is(bd.val(), '2018-01-01');
    t.is(bd.add(), '2018-01-03');
  });

  test('constructor reject 02', function(t) {
    var bd;
    bd = new bizday('2018-01-01', {
      reject: /\d{4}-01-\d{2}/
    });
    t.is(bd.val(), '2018-01-01');
    t.is(bd.add(), '2018-02-01');
  });

  test('constructor reject 03', function(t) {
    var bd;
    bd = new bizday('2018-01-01', {
      reject: [/\d{4}-01-\d{2}/, '-02-01']
    });
    t.is(bd.val(), '2018-01-01');
    t.is(bd.add(), '2018-02-02');
  });

  test('add(count)', function(t) {
    var bd;
    bd = new bizday('2018-07-02', {
      type: 'jp'
    });
    t.is(bd.add(15), '2018-07-24');
  });

  test('sub(count)', function(t) {
    var bd;
    bd = new bizday('2018-07-24', {
      type: 'jp'
    });
    t.is(bd.sub(15), '2018-07-02');
  });

}).call(this);
