// Generated by CoffeeScript 2.3.1
(function() {
  var _, bizday, moment, test;

  _ = require('lodash');

  bizday = require('../');

  moment = require('moment');

  ({test} = require('ava'));

  test('type is default', function(t) {
    var bd;
    bd = new bizday('20161229');
    t.is(bd.val(), '20161229');
    t.is(bd.add(), '20161230');
    t.is(bd.add(), '20170102');
    return t.is(bd.add(), '20170103');
  });

  test('type is tse', function(t) {
    var bd;
    bd = new bizday('20151229', {
      type: 'tse'
    });
    t.is(bd.val(), '20151229');
    t.is(bd.add(), '20151230');
    t.is(bd.add(), '20160104');
    return t.is(bd.add(), '20160105');
  });

  test('type is TSE', function(t) {
    var bd;
    bd = new bizday('20151229', {
      type: 'TSE'
    });
    t.is(bd.val(), '20151229');
    t.is(bd.add(), '20151230');
    t.is(bd.add(), '20160104');
    return t.is(bd.add(), '20160105');
  });

  test('type is Government', function(t) {
    var bd;
    bd = new bizday('20161227', {
      type: 'Government'
    });
    t.is(bd.val(), '20161227');
    t.is(bd.add(), '20161228');
    t.is(bd.add(), '20170104');
    return t.is(bd.add(), '20170105');
  });

  test('type is government', function(t) {
    var bd;
    bd = new bizday('20161227', {
      type: 'government'
    });
    t.is(bd.val(), '20161227');
    t.is(bd.add(), '20161228');
    t.is(bd.add(), '20170104');
    return t.is(bd.add(), '20170105');
  });

  test('type is go', function(t) {
    var bd;
    bd = new bizday('20161227', {
      type: 'go'
    });
    t.is(bd.val(), '20161227');
    t.is(bd.add(), '20161228');
    t.is(bd.add(), '20170104');
    return t.is(bd.add(), '20170105');
  });

  test('type is gov', function(t) {
    var bd;
    bd = new bizday('20161227', {
      type: 'gov'
    });
    t.is(bd.val(), '20161227');
    t.is(bd.add(), '20161228');
    t.is(bd.add(), '20170104');
    return t.is(bd.add(), '20170105');
  });

  test('type is unknown is default calendar', function(t) {
    var bd;
    bd = new bizday('20161227', {
      type: 'unknown'
    });
    t.is(bd.val(), '20161227');
    t.is(bd.add(), '20161228');
    t.is(bd.add(), '20161229');
    t.is(bd.add(), '20161230');
    t.is(bd.add(), '20170102');
    return t.is(bd.add(), '20170103');
  });

}).call(this);
